# Generated by Django 4.0.3 on 2022-03-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title_ru', models.TextField()),
                ('desc_ru', models.TextField()),
                ('title_en', models.TextField()),
                ('desc_en', models.TextField()),
                ('title_kg', models.TextField()),
                ('desc_kg', models.TextField()),
                ('gallery_id', models.TextField()),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
    ]
