# Generated by Django 4.0.3 on 2022-03-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='published',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
