# Generated by Django 4.0.3 on 2022-03-24 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_info_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ads_images<django.db.models.fields.related.ForeignKey>')),
                ('information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.info')),
            ],
        ),
    ]
