# Generated by Django 4.0.3 on 2022-03-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='images',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
