# Generated by Django 4.0.3 on 2022-03-23 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_subinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='subcategory',
        ),
    ]
