# Generated by Django 4.0.3 on 2022-03-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_about', '0002_remove_info_title_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='title_en',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='title_kg',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='title_ru',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='title_text_en',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='title_text_kg',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='title_text_ru',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
