# Generated by Django 4.0.3 on 2022-03-21 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_about', '0004_rename_title_text_en_info_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='address',
            new_name='title_text_en',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='desc_en',
            new_name='title_text_kg',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='desc_kg',
            new_name='title_text_ru',
        ),
        migrations.RemoveField(
            model_name='info',
            name='desc_ru',
        ),
        migrations.RemoveField(
            model_name='info',
            name='email',
        ),
        migrations.RemoveField(
            model_name='info',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='info',
            name='gallery_id',
        ),
        migrations.RemoveField(
            model_name='info',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='info',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='info',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='info',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='info',
            name='zoom',
        ),
    ]
